Repository DFE-Digital/find-a-lost-trn, pull requests merged in 2022-07, with the labels that each got.

#258 Fix docker image var for destroy
  .github/workflows/delete-review-app.yml
Labels: deploy

#288 Run matrix job sequentially
  .github/workflows/deploy.yml
Labels: DevOps

#292 Throw a better message if Notify key is missing
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
Labels: deploy

#309 Deploy Azure resources with new ARM template
  Makefile
Labels: DevOps

#302 Migrate Find to use new Azure resources
  terraform/terraform.tf
  terraform/workspace_variables/dev.backend.tfvars
  terraform/workspace_variables/dev.tfvars.json
  terraform/workspace_variables/preprod.backend.tfvars
  terraform/workspace_variables/preprod.tfvars.json
  terraform/workspace_variables/production.backend.tfvars
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/review.backend.tfvars
  terraform/workspace_variables/review.tfvars.json
  terraform/workspace_variables/test.backend.tfvars
  terraform/workspace_variables/test.tfvars.json
Labels: DevOps, deploy

#315 Fix storage details
  .github/workflows/delete-review-app.yml
Labels: deploy
