Repository DFE-Digital/find-a-lost-trn, pull requests merged in 2025-03, with the labels that each got.

#1168 feat: Adding OIDC for FALTRN
  .github/workflows/actions/database-backup/action.yml
  .github/workflows/actions/deploy/action.yml
  .github/workflows/actions/smoke-test/action.yml
  .github/workflows/aks-db-backup.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .tool-versions
  Makefile
  terraform/aks/.terraform.lock.hcl
  terraform/aks/provider.tf
Labels: DevOps, deploy

#1169 feat: CICD for domains
  .github/workflows/build-and-deploy.yml
  Makefile
  package.json
  terraform/domains/environment_domains/config/production.tfvars.json
  terraform/domains/environment_domains/main.tf
  terraform/domains/environment_domains/outputs.tf
  terraform/domains/environment_domains/variables.tf
  yarn.lock
Labels: DevOps, deploy

#1170 Correcting healthcheck path
  .github/workflows/build-and-deploy.yml
Labels: bug, DevOps

#1171 Correcting depednency for domains infra
  .github/workflows/build-and-deploy.yml
Labels: bug, DevOps

#1172 Update db workflows
  .github/workflows/actions/database-backup/action.yml
  .github/workflows/aks-db-backup.yml
  .github/workflows/database-restore-ptr.yml
  .github/workflows/database-restore.yml
Labels: DevOps

#1173 Adding id-token permission to workflow
  .github/workflows/build-nocache.yml
Labels: DevOps

#1174 Adding maintenance page and workflow
  .github/workflows/maintenance.yml
  Makefile
  maintenance_page/Dockerfile
  maintenance_page/html/assets/fonts/bold-affa96571d-v2-b092ddd6.woff
  maintenance_page/html/assets/fonts/bold-b542beb274-v2-616e5f21.woff2
  maintenance_page/html/assets/fonts/light-94a07e06a1-v2-bb962e0c.woff2
  maintenance_page/html/assets/fonts/light-f591b13f7d-v2-f03d82c2.woff
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico.br
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico.gz
  maintenance_page/html/assets/images/favicon-ec189703.svg
  maintenance_page/html/assets/images/favicon-ec189703.svg.br
  maintenance_page/html/assets/images/favicon-ec189703.svg.gz
  maintenance_page/html/assets/images/govuk-crest-2x.png
  maintenance_page/html/assets/images/govuk-crest.png
  maintenance_page/html/assets/images/govuk-icon-180-e0835e78.png
  maintenance_page/html/assets/images/govuk-icon-192-7b8e00f8.png
  maintenance_page/html/assets/images/govuk-icon-512-587f7e53.png
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg.br
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg.gz
  maintenance_page/html/assets/images/govuk-opengraph-image-bd4c811b.png
  maintenance_page/html/assets/images/icon-close-cross-black-692c7df5.svg
  maintenance_page/html/assets/images/icon-close-cross-black-692c7df5.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg.gz
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg.gz
  maintenance_page/html/assets/images/icon-toggle-plus-minus-257426a1.svg
  maintenance_page/html/index.html
  maintenance_page/html/javascript/govuk-frontend-5.3.1.min.js
  maintenance_page/html/stylesheets/govuk-frontend-5.3.1.min.css
  maintenance_page/manifests/maintenance/deployment_maintenance.yml
  maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
  maintenance_page/manifests/maintenance/service_maintenance.yml
  maintenance_page/manifests/preproduction/ingress_internal_to_main.yml
  maintenance_page/manifests/preproduction/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/preproduction/ingress_maintenance.yml
  maintenance_page/manifests/preproduction/ingress_temp_to_main.yml
  maintenance_page/manifests/production/ingress_internal_to_main.yml
  maintenance_page/manifests/production/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/production/ingress_maintenance.yml
  maintenance_page/manifests/production/ingress_temp_to_main.yml
  maintenance_page/manifests/test/ingress_internal_to_main.yml
  maintenance_page/manifests/test/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/test/ingress_maintenance.yml
  maintenance_page/manifests/test/ingress_temp_to_main.yml
  maintenance_page/nginx.conf
  maintenance_page/scripts/failback.sh
  maintenance_page/scripts/failover.sh
Labels: DevOps
